services:
  memcached:
    image: memcached:latest
    ports:
      - 11211:11211
  # redis:
  #   image: redis:latest
  #   ports:
  #     - 6379:6379
  valkey:
    image: valkey/valkey:unstable
    ports:
      - 6379:6379